AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  FamilyService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: FamilyService/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /tellmommy/family
            Method: ANY
  FamilyServicePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - FamilyService
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
  ChoreService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: ChoreService/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: >-
        arn:aws:iam::207843647879:role/cloud9-TellMommyServices-FamilyServiceRole-1BFQUKKX5XRUJ
  ChoreActivityService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: ChoreActivityService/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: >-
        arn:aws:iam::207843647879:role/cloud9-TellMommyServices-FamilyServiceRole-1BFQUKKX5XRUJ
  LoginService:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: LoginService/index.handler
      Runtime: nodejs6.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role: >-
        arn:aws:iam::207843647879:role/cloud9-TellMommyServices-FamilyServiceRole-1BFQUKKX5XRUJ
